# Generated by Django 5.2.17 on 2026-08-21 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(choices=[('GI', 'GI'), ('INTERNATIONAL', 'International'), ('HUF', 'HUF'), ('LLP', 'LLP'), ('GWT', 'GWT')], max_length=20)),
                ('compliance_type', models.CharField(choices=[('TDS_PAYMENT', 'TDS Payment'), ('GSTR_1', 'GSTR-1'), ('GSTR_3B', 'GSTR-3B')], max_length=20)),
                ('month', models.IntegerField(help_text='Month number (1-12)')),
                ('year', models.IntegerField(help_text='4-digit Year (e.g. 2026)')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done')], default='PENDING', max_length=10)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('reference_number', models.CharField(blank=True, default='', help_text='Challan/Ref No.', max_length=100)),
                ('document_link', models.URLField(blank=True, default='', help_text='Reference document URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_compliance_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company', 'compliance_type'],
                'unique_together': {('company', 'compliance_type', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ComplianceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_comments', to=settings.AUTH_USER_MODEL)),
                ('compliance_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='compliance.complianceitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
