# Generated by Django 5.2.17 on 2026-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceitem',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DONE', 'Done'), ('NOT_APPLICABLE', 'N/A')], default='PENDING', max_length=20),
        ),
    ]
