# Generated by Django 5.2.17 on 2026-08-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0002_alter_complianceitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceitem',
            name='compliance_type',
            field=models.CharField(choices=[('TDS_PAYMENT', 'TDS Payment'), ('GSTR_1', 'GSTR-1'), ('GSTR_3B', 'GSTR-3B'), ('TDS_RETURN_Q1', 'TDS Return Q1'), ('TDS_RETURN_Q2', 'TDS Return Q2'), ('TDS_RETURN_Q3', 'TDS Return Q3'), ('TDS_RETURN_Q4', 'TDS Return Q4')], max_length=20),
        ),
    ]
