# Generated by Django 5.2.17 on 2026-08-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0003_alter_complianceitem_compliance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complianceitem',
            name='company',
            field=models.CharField(choices=[('GI', 'GI'), ('INTERNATIONAL', 'International'), ('HUF', 'HUF'), ('LLP', 'LLP'), ('GTW', 'GTW')], max_length=20),
        ),
    ]
