services:
  - type: web
    name: gemini-updates
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn gemini_updates.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: gemini-updates
          property: host
