# Generated by Django 5.2.17 on 2026-08-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_helper',
            field=models.BooleanField(default=False, help_text='Helper role who can mark compliance items as N/A'),
        ),
    ]
