# Generated by Django 5.2.17 on 2026-09-09 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_dailytaskreport_status_assignedtask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtask',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='boss_remark',
            field=models.TextField(blank=True, default='', help_text='Feedback or remarks from Boss requesting revisions or noting issues.'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='is_reallocated',
            field=models.BooleanField(default=False, help_text='Indicates whether this task was delegated to another employee.'),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='original_assigned_to',
            field=models.ForeignKey(blank=True, help_text='The initial employee the boss allocated this task to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originally_assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assignedtask',
            name='reallocation_reason',
            field=models.TextField(blank=True, default='', help_text='Latest reallocation explanation.'),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='assigned_to',
            field=models.ForeignKey(help_text='Current employee responsible for completing the task.', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignedtask',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('WAITING_APPROVAL', 'Waiting Approval'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_REALLOCATED', 'Task Reallocated'), ('TASK_COMPLETED_WAITING_APPROVAL', 'Task Completed (Waiting Approval)'), ('TASK_APPROVED', 'Task Approved'), ('TASK_REVISION_REQUESTED', 'Task Revision Requested (Remark Added)'), ('DAILY_REPORT_COMMENT', 'Daily Report Comment'), ('GENERAL', 'General Notification')], default='GENERAL', max_length=40)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='reports.assignedtask')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskReallocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for transferring the task to another employee.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reallocated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_made', to=settings.AUTH_USER_MODEL)),
                ('reallocated_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations_received', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reallocations', to='reports.assignedtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_remarks_given', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='reports.assignedtask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
