# Generated by Django 5.2.17 on 2026-09-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_assignedtask_approved_at_assignedtask_boss_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
